### ISSUE TITLE
Local eval demo

### ISSUE THREAD

**Issue by Kin-Zhang** [kylevedder/BucketedSceneFlowEval#2]
Hi, nice work!

Let us know when it's ready to run, since I saw there are some function is missing.

```python
# Import abstract base class for evaluator
from abc import ABC, abstractmethod
from typing import Any

from bucketed_scene_flow_eval.datastructures import (
    EstimatedPointFlow,
    GroundTruthPointFlow,
    Timestamp,
)


class Evaluator(ABC):
    @abstractmethod
    def eval(
        self,
        predictions: EstimatedPointFlow,
        ground_truth: GroundTruthPointFlow,
        query_timestamp: Timestamp,
    ):
        pass

    @abstractmethod
    def compute_results(self, save_results: bool = True) -> dict[Any, Any]:
        pass
```

And also maybe give a local example result in the README so people can know in advance about the metric we use here.

**Comment by kylevedder** [comment]
The eval protocol is fully implemented in  [`bucketed_scene_flow_eval/eval/bucketed_epe.py`](https://github.com/kylevedder/BucketedSceneFlowEval/blob/master/bucketed_scene_flow_eval/eval/bucketed_epe.py); the `eval.py` file you linked to is an abstract base class that defines the API spec for implementing other future evaluation protocols.

If you want to try out the eval protocol right now, it's hooked up to the validation eval of [SceneFlowZoo](https://github.com/kylevedder/SceneFlowZoo) or you can run it against dumped standalone data from the Zoo (see the instructions at the bottom of the Zoo README, but use the `val` instead of `test` split)  with our [`av2_eval.py`](https://github.com/kylevedder/BucketedSceneFlowEval/blob/master/scripts/evals/av2_eval.py) script (this is the exact eval script running behind the scenes on the EvalAI leaderboard).

I'll update the README with a link to the AV2 2024 Scene Flow Challenge blogpost and add some of the explanatory material for the actual metric.

**Comment by kylevedder** [comment]
For reference, this is how the `Evaluator` is constructed for 

Argoverse 2:

https://github.com/kylevedder/BucketedSceneFlowEval/blob/master/bucketed_scene_flow_eval/datasets/argoverse2/dataset.py#L272-L279

Waymo Open:

https://github.com/kylevedder/BucketedSceneFlowEval/blob/master/bucketed_scene_flow_eval/datasets/waymoopen/dataset.py#L194-L199

**Comment by Kin-Zhang** [comment]
![image](https://github.com/kylevedder/BucketedSceneFlowEval/assets/35365764/f57dc891-2c22-4e64-9076-181bfde5bdc3)

I don't understand why we need transfer to idx? The first leaderboard, holds a better file name which is exactly the name of the sequence and timestamp:

![image](https://github.com/kylevedder/BucketedSceneFlowEval/assets/35365764/41dc20b2-9dae-4545-bbfa-1e3c183e8be2)

Could we use the previous zip format (with one more meta json included) and submit to the second leaderboard?

More specifically could we have a format description like this one: https://argoverse.github.io/user-guide/tasks/3d_scene_flow.html

**Comment by kylevedder** [comment]
There's a couple reasons why I chose to use per-sequence relative indexing instead of AV2 timestamps:

1) There's actually a bit of ambiguity on what timestamp should be associated with a flow: a flow describes motion from t_1 to t_2, so what should its timestamp really be? People typically label it with t_1, but that's a non-obvious convention.

2) Relative indexing makes it easier to do validation checks and call out exactly what files are missing. I do this in my [preparation scripts for leaderboard eval](https://github.com/kylevedder/BucketedSceneFlowEval/blob/master/scripts/evals/setup_sparse_user_submission.py). 

3) It's a more general format that's not AV2 specific; you can just as easily use any other dataset in this multi-sequence format.

It's easy to convert from AV2 timestamp to relative index, and once things are labeled with a relative index a bunch of operations become a lot easier.

**Comment by Kin-Zhang** [comment]
Great, Thanks! Let me try it.

Maybe I will upload a corresponding pkl file like the following, so that makes people from 1st leaderboard to 2nd easier 😅 without struggling to figure out the relative indexing afterward: 
```
idx(10d)             scene_id      timestamp
0000000000           xxx           xxx
0000000005           xxx           xxx
0000000010           xxx           xxx
```

**Comment by Kin-Zhang** [comment]
I found out the python version is only >=3.10 (I believe most of people still py38), 
is that easy for you to provide the pkl file like above? Looks like not easy for me, still deal with lots of stuff. 

btw, some docker is not on the dockerhub. `bucketed_scene_flow_eval:latest`


---

16mins later: OK, I think I figure out.. Let me check if it's correct.

**Comment by kylevedder** [comment]
There's a number of performance and ergonomic improvements (e.g. better error messages) in Python 3.10, which is why we chose to use it. 3.10 was released over 2 years ago at this point (October 2021) so there should be 3.10 versions for all of your dependencies.

`bucketed_scene_flow_eval:latest` is on dockerhub at: https://hub.docker.com/repository/docker/kylevedder/bucketed_scene_flow_eval/general

**Comment by kylevedder** [comment]
Regarding the pickle file:

That should just be a sweep through the AV2 dataset sequence folder and then each sequence lidar pointcloud name. We're pushing for the ECCV deadline (we're cooking up something new 🧑🏻‍🍳) so I don't have time to write it now.

Honestly you should just be able to get ChatGPT to write it. If you think it's generally useful, feel free to drop it in a PR and I can take a look later.

**Comment by Kin-Zhang** [comment]
One more question, why do we need to write valid?
![image](https://github.com/kylevedder/BucketedSceneFlowEval/assets/35365764/bcbe8a23-5464-4fc7-963e-9e879858aa42)

For if one method says most of points is not valid, how does the leaderboard say whether to count this accuracy or not? I thought the valid should be the same for all methods. But not cases like: one method said it's not valid for me, you shouldn't calculate error in this point, etc.

**Comment by kylevedder** [comment]
I use this data format for everything in the SceneFlowZoo -- the output of the ground truth generation script, the output of model dumpers, and the submission format for the competition. As part of this data format, the `is_valid` column allows you to indicate if a point was skipped or not by your flow method, or if it was out of range, or some other reason.

As part of evaluation, we expect that every point which is indicated as valid by the ground truth (with the ground points removed) will be labeled as valid in the submission. [As part of evaluation, error is raised if the GT flow indicates a point is valid but the target estimates indicate it's not.](https://github.com/kylevedder/BucketedSceneFlowEval/blob/a82efb06b4fb5e03de9d38326072e73f317e9e13/bucketed_scene_flow_eval/eval/base_per_frame_sceneflow_eval.py#L266-L269)

**Comment by Kin-Zhang** [comment]
I see. Thank you so much for your time! ❤️ Best wishes to all our submissions also.
I think I figured it out finally.
